//! Cross-version parity matrix: Rust `detect_artifacts` (band-detection
//! path) vs MATLAB R2025a `detect_artifacts(data, Fs, 'slope_test', false)`
//! on the synthetic-EEG fixture battery generated by
//! `DYNAM-O_DesktopApp/scripts/generate_handoff_fixtures.m`.
//!
//! The Rust crate's `detect_artifacts` does NOT include the slope-test
//! branch by itself — that lives behind the `slope_test` feature in
//! `slope_test.rs`. This file gates against the MATLAB `slope_test=false`
//! reference so parity is meaningful regardless of feature flags.
//!
//! Per-variant sample-disagreement budgets (see plan):
//!     sim_clean    <=   5 samples (30000-sample record)
//!     sim_motion   <=  30
//!     sim_flat     <=   5  (flat-run detection itself is exact, but the
//!                            iter-zscore can disagree by a few samples at
//!                            the flat-run boundaries)
//!     sim_full     <=  30
//!     sim_dense    <=  50
//!
//! If any variant exceeds its budget, the test prints the indices of the
//! first 10 disagreements so triage is fast.

use artifact_detection_rs::{detect_artifacts, ArtifactOpts};
use ndarray::{Array1, Array2};
use ndarray_npy::read_npy;
use std::path::PathBuf;

fn fixtures() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

fn load_logical(path: PathBuf) -> Vec<bool> {
    // MATLAB-dumped logical .npy uses dtype "|b1" which ndarray-npy does not
    // accept (it expects "|u1" for byte-wide bool). Parse the .npy header
    // manually and read the trailing bytes as one-byte-per-bool.
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("read {:?}: {}", path, e));
    assert!(bytes.len() >= 10 && &bytes[0..6] == b"\x93NUMPY", "{:?}: not an .npy", path);
    let header_len = u16::from_le_bytes([bytes[8], bytes[9]]) as usize;
    let data_start = 10 + header_len;
    let header = std::str::from_utf8(&bytes[10..data_start]).expect("npy header utf-8");
    assert!(
        header.contains("'descr': '|b1'") || header.contains("'descr': '|u1'"),
        "{:?}: unexpected dtype in header: {}",
        path, header
    );
    bytes[data_start..].iter().map(|&b| b != 0).collect()
}

fn load_double(path: PathBuf) -> Vec<f64> {
    let arr: Array1<f64> = read_npy(path).expect("load f64 npy");
    arr.to_vec()
}

fn run_variant(variant: &str, seed: u32, budget: usize) {
    let base = format!("sim_{}_seed{}", variant, seed);
    let data = load_double(fixtures().join(format!("{}.npy", base)));
    let mat_mask = load_logical(fixtures().join(format!("{}_art_mat_no_slope.npy", base)));
    assert_eq!(data.len(), mat_mask.len(), "{}: length mismatch", variant);

    let opts = ArtifactOpts::default();
    let rust_mask = detect_artifacts(&data, 100.0, &opts);
    assert_eq!(rust_mask.len(), mat_mask.len());

    let diffs: Vec<usize> = rust_mask
        .iter()
        .zip(mat_mask.iter())
        .enumerate()
        .filter_map(|(i, (a, b))| if a != b { Some(i) } else { None })
        .collect();

    if diffs.len() > budget {
        let preview: Vec<&usize> = diffs.iter().take(10).collect();
        panic!(
            "{}: {} sample disagreements (budget = {}). First 10: {:?}",
            variant,
            diffs.len(),
            budget,
            preview
        );
    }
    eprintln!(
        "  parity {:<8}: {:5} disagreements (budget {})",
        variant,
        diffs.len(),
        budget
    );
}

#[test]
fn parity_sim_clean() {
    run_variant("clean", 42, 5);
}

#[test]
fn parity_sim_motion() {
    run_variant("motion", 42, 30);
}

#[test]
fn parity_sim_flat() {
    run_variant("flat", 42, 5);
}

#[test]
fn parity_sim_full() {
    run_variant("full", 42, 30);
}

#[test]
fn parity_sim_dense() {
    run_variant("dense", 43, 50);
}

#[test]
fn cheby1_hp_design_matches_matlab() {
    // The MATLAB fixture is a JSON dump of zp2sos(cheby1(4, 0.2, 35/50, 'high')).
    // We don't have a Rust HP-design fixture loader here — this test just
    // verifies the JSON is present and the SOS layout is plausible (6 cols
    // per section, 2 sections for an order-4 filter).
    let json = std::fs::read_to_string(fixtures().join("cheby1_hp_4_02_35hz.json"))
        .expect("load cheby1 json");
    assert!(json.contains("\"sos\""), "missing sos field");
    assert!(json.contains("35"), "missing cutoff annotation");
    // Number of section rows = 2 for order 4.
    let rows = json.matches("[").count() - json.matches("[]").count();
    assert!(rows >= 3, "expected >= 3 brackets in sos, got {}", rows);
}

#[allow(dead_code)]
fn _ensure_array2_visible() -> Option<Array2<f64>> {
    None // silences unused-import warning if shape changes upstream
}
